name: fontic

# App description
description: "A premium Flutter font explorer app."

# Prevents accidental publishing to pub.dev
publish_to: "none"

# App version
# Format: version_name+build_number
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.11.5

# --------------------------------------------------
# APP DEPENDENCIES
# --------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # Cupertino style icons for iOS look
  cupertino_icons: ^1.0.8

  # Google Fonts integration
  google_fonts: ^8.1.0

  # Font Awesome icons package
  font_awesome_flutter: ^11.0.0

  # Modern Lucide icons
  lucide_icons: ^0.257.0

  # Local storage for saving liked fonts
  shared_preferences: ^2.5.5

# --------------------------------------------------
# DEV DEPENDENCIES
# --------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended Flutter lint rules
  flutter_lints: ^6.0.0

  # Package used for generating app launcher icons
  flutter_launcher_icons: ^0.14.4

# --------------------------------------------------
# FLUTTER SETTINGS
# --------------------------------------------------
flutter:
  # Enables Material icons
  uses-material-design: true

  # Assets folder
  # Uncomment if you add images/assets later
  #
  # assets:
  #   - assets/images/
  #   - assets/icons/

# --------------------------------------------------
# APP ICON CONFIGURATION
# --------------------------------------------------
flutter_launcher_icons:
  # Generate launcher icon for Android
  android: true

  # Generate launcher icon for iOS
  ios: true

  # Path of your app icon image
  image_path: "assets/icons/app_icon.png"
